apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argocd
  namespace: kube-system
spec:
  chart: argo-cd
  repo: https://argoproj.github.io/argo-helm
  targetNamespace: argocd
  valuesContent: |-
    server:
      extraArgs:
        - --insecure
      ingress:
        enabled: true
        hosts:
          - argocd.atoy.dev